turn_on:
  name: Turn On Talkback
  description: Start 2-way audio talkback to a UniFi Protect camera
  target:
    entity:
      domain: switch
      integration: unifiprotect_2way_audio

turn_off:
  name: Turn Off Talkback
  description: Stop 2-way audio talkback to a UniFi Protect camera
  target:
    entity:
      domain: switch
      integration: unifiprotect_2way_audio
